version: "3"

services:
  reverse-proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - letsencrypt:/letsencrypt
    labels:
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.testHeader.headers.customrequestheaders.Pragma=no-cache"

  webserver:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`localhost`)"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=myresolver"
      - "traefik.http.routers.webserver.entrypoints=web,websecure"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"

volumes:
  letsencrypt: