debug: true
logLevel: DEBUG

providers:
  docker:
    exposedByDefault: false
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "idquantum@gmail.com"
      storage: /letsencrypt/acme.json
      tlschallenge: true
      httpChallenge:
        entryPoint: web